### ISSUE TITLE
send Message error caused by puppeteer disconnect browser before sending

### ISSUE THREAD

**Issue by log901108** [SwapnilSoni1999/messages-web#13]
C:\Users\v\Desktop\RN\gsms>node sendSms.js
Sending message...
retrying...
Message sent!
C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51
            helper_js_1.helper.addEventListener(frameManager._client, Connection_js_1.CDPSessionEmittedEvents.Disconnected, () => this._terminate(new Error('Navigation failed because browser has disconnected!'))),
                                                                                                                                                  ^

Error: Navigation failed because browser has disconnected!
    at C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
    at C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onClosed (C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:247:14)
    at Connection._onClose (C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:128:21)
    at WebSocket.<anonymous> (C:\Users\v\Desktop\RN\gsms\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (C:\Users\v\Desktop\RN\gsms\node_modules\ws\lib\event-target.js:136:16)
    at WebSocket.emit (node:events:513:28)

**Comment by log901108** [comment]
I think google message changed logic for sending message please change logic in send message function in lib
